### ISSUE TITLE
建议增加 requirements 文件，以及 python 版本说明

### ISSUE THREAD

**Issue by drcege** [fooofei/py_netease_music#1]
正需要整个功能，还好找到你这个代码了，不过使用还是有点问题~

1.  `io_in_out.py` 文件说明在 Readme 中间，很容易被忽略，还有 `browsercookie` 依赖
2.  不明确 python 版本，我用 python3会报 `'filter' object is not subscriptable`，没有做兼容，至少说明一下
3.  所有功能都得自己写啊…… 能不能提供几个简单的案例实现，比如提到的排序功能

**Comment by fooofei** [comment]
收到建议。
